#
#
#	Makefile for HDK libraries
#
#	Written by Jongwon Kim
#		2013. 11. 14.
#

################################################################
MAKE    := make -C
################################################################

SILENT      ?= @

all: sedec

.PHONY: sedec
sedec:
	$(MAKE) sedec
	
.PHONY: clean
clean:
	$(MAKE) sedec clean
	
.PHONY: distclean
distclean: clean
